import 'package:flutter_test/flutter_test.dart';
import 'package:nekovision/invidious/caption.dart';

void main() {
  group('Caption from_json', () {
    test('correctly parses a JSON object into a Caption object', () {
      final Map<String, dynamic> sample_json = {
        'languageCode': 'en',
        'label': 'English',
        'url': 'https://example.com/caption.vtt',
        'isAutoGenerated': true,
      };

      final result = from_json(sample_json);

      expect(result.language_code, 'en');
      expect(result.label, 'English');
      expect(result.url, 'https://example.com/caption.vtt');
    });
  });
}